// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpsSphere.Infrastructure.Persistence;

#nullable disable

namespace OpsSphere.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OpsSphereDbContext))]
    [Migration("20260518164113_AddSlaStateAtRiskThreshold")]
    partial class AddSlaStateAtRiskThreshold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpsSphere.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Accounts_Code");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("IX_Accounts_CountryId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Accounts_IsActive");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("IX_AuditLogs_ActorUserId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditLogs_CorrelationId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_CreatedAt");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityType_EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Campaigns_AccountId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Campaigns_Code");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("IX_Campaigns_CountryId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Campaigns_IsActive");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Countries_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Countries_IsActive");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("IX_Countries_RegionId");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Customers_AccountId");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Customers_Email");

                    b.HasIndex("ExternalReference")
                        .HasDatabaseName("IX_Customers_ExternalReference");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Customers_IsActive");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Permissions_Code");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Regions_Code");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Name");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_RolePermissions_PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.SlaPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AtRiskThresholdPercent")
                        .HasColumnType("int");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TargetHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_SlaPolicies_AccountId");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("IX_SlaPolicies_CampaignId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_SlaPolicies_IsActive");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_SlaPolicies_Priority");

                    b.HasIndex("AccountId", "CampaignId", "Priority")
                        .HasDatabaseName("IX_SlaPolicies_AccountId_CampaignId_Priority");

                    b.ToTable("SlaPolicies", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedAgentUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SlaDueAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SlaState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("SupervisorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Tickets_AccountId");

                    b.HasIndex("AssignedAgentUserId")
                        .HasDatabaseName("IX_Tickets_AssignedAgentUserId");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("IX_Tickets_CampaignId");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("IX_Tickets_CountryId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Tickets_CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Tickets_CustomerId");

                    b.HasIndex("IsEscalated")
                        .HasDatabaseName("IX_Tickets_IsEscalated");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_Tickets_Priority");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("IX_Tickets_RegionId");

                    b.HasIndex("SlaDueAt")
                        .HasDatabaseName("IX_Tickets_SlaDueAt");

                    b.HasIndex("SlaState")
                        .HasDatabaseName("IX_Tickets_SlaState");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Tickets_Status");

                    b.HasIndex("SupervisorUserId")
                        .HasDatabaseName("IX_Tickets_SupervisorUserId");

                    b.HasIndex("TicketNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Tickets_TicketNumber");

                    b.HasIndex("AssignedAgentUserId", "Status")
                        .HasDatabaseName("IX_Tickets_AssignedAgentUserId_Status");

                    b.HasIndex("SlaState", "SlaDueAt")
                        .HasDatabaseName("IX_Tickets_SlaState_SlaDueAt");

                    b.HasIndex("SupervisorUserId", "Status")
                        .HasDatabaseName("IX_Tickets_SupervisorUserId_Status");

                    b.HasIndex("AccountId", "CampaignId", "Status")
                        .HasDatabaseName("IX_Tickets_AccountId_CampaignId_Status");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.TicketAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NewAgentUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PreviousAgentUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("IX_TicketAssignments_AssignedByUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_TicketAssignments_CreatedAt");

                    b.HasIndex("NewAgentUserId")
                        .HasDatabaseName("IX_TicketAssignments_NewAgentUserId");

                    b.HasIndex("PreviousAgentUserId");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_TicketAssignments_TicketId");

                    b.ToTable("TicketAssignments", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("IX_TicketComments_AuthorUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_TicketComments_CreatedAt");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_TicketComments_TicketId");

                    b.ToTable("TicketComments", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.TicketEscalation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EscalatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EscalationReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_TicketEscalations_CreatedAt");

                    b.HasIndex("EscalatedByUserId")
                        .HasDatabaseName("IX_TicketEscalations_EscalatedByUserId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TicketEscalations_IsActive");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("IX_TicketEscalations_ReviewedByUserId");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_TicketEscalations_TicketId");

                    b.ToTable("TicketEscalations", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.TicketResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalSlaState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResolutionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResolutionSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResolvedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_TicketResolutions_CreatedAt");

                    b.HasIndex("FinalSlaState")
                        .HasDatabaseName("IX_TicketResolutions_FinalSlaState");

                    b.HasIndex("ResolvedByUserId")
                        .HasDatabaseName("IX_TicketResolutions_ResolvedByUserId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("TicketResolutions", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.TicketSlaState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AtRiskThresholdPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(80);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastEvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SlaPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("IX_TicketSlaStates_DueAt");

                    b.HasIndex("LastEvaluatedAt")
                        .HasDatabaseName("IX_TicketSlaStates_LastEvaluatedAt");

                    b.HasIndex("SlaPolicyId");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_TicketSlaStates_State");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("UQ_TicketSlaStates_TicketId");

                    b.HasIndex("State", "DueAt")
                        .HasDatabaseName("IX_TicketSlaStates_State_DueAt");

                    b.ToTable("TicketSlaStates", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.TicketStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("IX_TicketStatusHistory_ChangedByUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_TicketStatusHistory_CreatedAt");

                    b.HasIndex("NewStatus")
                        .HasDatabaseName("IX_TicketStatusHistory_NewStatus");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_TicketStatusHistory_TicketId");

                    b.ToTable("TicketStatusHistory", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.UserScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_UserScopes_AccountId");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("IX_UserScopes_CampaignId");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("IX_UserScopes_CountryId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_UserScopes_IsActive");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("IX_UserScopes_RegionId");

                    b.HasIndex("ScopeType")
                        .HasDatabaseName("IX_UserScopes_ScopeType");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserScopes_UserId");

                    b.HasIndex("UserId", "ScopeType", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserScopes_User_Account")
                        .HasFilter("[AccountId] IS NOT NULL");

                    b.HasIndex("UserId", "ScopeType", "CampaignId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserScopes_User_Campaign")
                        .HasFilter("[CampaignId] IS NOT NULL");

                    b.HasIndex("UserId", "ScopeType", "CountryId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserScopes_User_Country")
                        .HasFilter("[CountryId] IS NOT NULL");

                    b.HasIndex("UserId", "ScopeType", "RegionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserScopes_User_Region")
                        .HasFilter("[RegionId] IS NOT NULL");

                    b.ToTable("UserScopes", (string)null);
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Account", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.Country", "Country")
                        .WithMany("Accounts")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.Account", "Account")
                        .WithMany("Campaigns")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.Country", "Country")
                        .WithMany("Campaigns")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Country", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Customer", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.Account", "Account")
                        .WithMany("Customers")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.SlaPolicy", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.Account", "Account")
                        .WithMany("SlaPolicies")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpsSphere.Domain.Entities.Campaign", "Campaign")
                        .WithMany("SlaPolicies")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.User", "AssignedAgentUser")
                        .WithMany()
                        .HasForeignKey("AssignedAgentUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpsSphere.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.User", "SupervisorUser")
                        .WithMany()
                        .HasForeignKey("SupervisorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("AssignedAgentUser");

                    b.Navigation("Campaign");

                    b.Navigation("Country");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Region");

                    b.Navigation("SupervisorUser");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.TicketAssignment", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.User", "NewAgentUser")
                        .WithMany()
                        .HasForeignKey("NewAgentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.User", "PreviousAgentUser")
                        .WithMany()
                        .HasForeignKey("PreviousAgentUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpsSphere.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Assignments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("NewAgentUser");

                    b.Navigation("PreviousAgentUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.TicketComment", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.TicketEscalation", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.User", "EscalatedByUser")
                        .WithMany()
                        .HasForeignKey("EscalatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpsSphere.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Escalations")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EscalatedByUser");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.TicketResolution", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.Ticket", "Ticket")
                        .WithOne("Resolution")
                        .HasForeignKey("OpsSphere.Domain.Entities.TicketResolution", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResolvedByUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.TicketSlaState", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.SlaPolicy", "SlaPolicy")
                        .WithMany("TicketSlaStates")
                        .HasForeignKey("SlaPolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpsSphere.Domain.Entities.Ticket", "Ticket")
                        .WithOne("SlaStateRecord")
                        .HasForeignKey("OpsSphere.Domain.Entities.TicketSlaState", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlaPolicy");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.TicketStatusHistory", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.Ticket", "Ticket")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpsSphere.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.UserScope", b =>
                {
                    b.HasOne("OpsSphere.Domain.Entities.Account", "Account")
                        .WithMany("UserScopes")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpsSphere.Domain.Entities.Campaign", "Campaign")
                        .WithMany("UserScopes")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpsSphere.Domain.Entities.Country", "Country")
                        .WithMany("UserScopes")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpsSphere.Domain.Entities.Region", "Region")
                        .WithMany("UserScopes")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpsSphere.Domain.Entities.User", "User")
                        .WithMany("UserScopes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Campaign");

                    b.Navigation("Country");

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Account", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Customers");

                    b.Navigation("SlaPolicies");

                    b.Navigation("UserScopes");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("SlaPolicies");

                    b.Navigation("UserScopes");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Country", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Campaigns");

                    b.Navigation("UserScopes");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Region", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("UserScopes");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.SlaPolicy", b =>
                {
                    b.Navigation("TicketSlaStates");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Comments");

                    b.Navigation("Escalations");

                    b.Navigation("Resolution");

                    b.Navigation("SlaStateRecord");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("OpsSphere.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("UserScopes");
                });
#pragma warning restore 612, 618
        }
    }
}
